---
title: "Markdown Lab"
author: "Kirill Musaev"
date: "3/1/2021"
output:
  html_document: 
    toc: TRUE #add table of contents
    toc_float: TRUE #floating TOC on the left
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE#,
                      #warning = FALSE #put "show" settings here such as hide warnings globally
                      )
```

# Header with 1 pound
## Header with 2 pounds
*Italics* in asterisks, **bold** in 2 sets of asterisks

## Load Libraries
```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(palmerpenguins)
library(here)

```

# Inspect the data
```{r}
glimpse(penguins)
```

# Make a plot
```{r}
penguins %>% #open pipeline for graph
  ggplot(aes(x = bill_length_mm, #define axes
             y = bill_depth_mm, 
             color = species)
         )+
  geom_point()+ #place scatter
  geom_smooth(method = "lm")+ #trendline, linear model
  labs(x = "Bill length (mm)", #add labels
       y = "Bill Depth (mm)"
       )+
  theme_bw()
```

