---
title: "W6_Wed"
author: "Kirill Musaev"
date: "3/3/2021"
output:
  html_document: 
    toc: TRUE #add table of contents
    toc_float: TRUE #floating TOC on the left
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Using Palmer penguins data to build figures in RMarkdown

# Load Libraries
```{r, message = FALSE, warning = FALSE}
library(palmerpenguins)
library(tidyverse)
library(here)
library(kableExtra)
```

# Make a Plot
```{r PengFig, fig.align="center", fig.cap="Flippers by species", echo = FALSE, fig.path = "../Output/"}
PenguinFigure <- penguins %>%
  ggplot(aes(x = species, y = flipper_length_mm, color = island)) +
  geom_boxplot()

PenguinFigure
```

# Manual table

The ":--", ":--:", "--:" symbols in the code are left, center and right alignment respectively

| Time  | Session | Topic    |
|:------|:-------:|---------:| 
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

```{r}
penguins %>%
  group_by(species) %>%
  summarize(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold=TRUE, color="white", background="red")
```

