---
title: "W7_Mon_CW"
author: "Kirill Musaev"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, echo = FALSE}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
```
```{r load_data, echo = FALSE}
# Read in data on population in California by county
popdata<-read_csv(here("Week_7","data","CApopdata.csv"))
#read in data on number of seastars at different field sites
stars<-read_csv(here("Week_7","data","stars.csv"))
```

```{r data_analysis}
# get data for the entire world
world<-map_data("world")
head(world) #check loaded data

#load USA data
usa<-map_data("usa")
#head(usa)
#can do the same with states and counties
states<-map_data("state")
counties<-map_data("county")
```
```{r world_map}
ggplot()+ #displaying a simple map:
  geom_polygon(data = world, #part of the mapdata package
               aes(x = long, #set axes
                   y = lat, 
                   group = group, #necessary for correct rendering
                   fill = region),#colors for different countries
               color = "black") + #make borders black
  guides(fill=FALSE)+
  theme_minimal()+ #thin lines?
  theme(panel.background = element_rect(fill = "lightblue"))+ #change water color
  coord_map(projection = "mercator", #allows to change projection
            xlim = c(-180,180)) #set coordinates for the center of the projection



```
```{r cali_map}
CA_data<-states %>%
  filter(region == "california")

ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "black")+
  coord_map()+
  theme_void()

CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% 
  inner_join(counties) %>%
  filter(region == "california")

ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ 
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2") +
  ggsave(here("Week_7","output","CApop.pdf"))
```

